// Code generated by qtc from "release_email.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line release_email.qtpl:1
package ghdeploy

//line release_email.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line release_email.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line release_email.qtpl:1
func (d *Deployer) streamrenderReleaseEmail(qw422016 *qt422016.Writer, newReleaseTag string, c compareResponse) {
//line release_email.qtpl:1
	qw422016.N().S(`
<div>
  <strong>Changes in this release:</strong>
</div>
<table>
  <tbody>
    `)
//line release_email.qtpl:7
	for _, commit := range c.Commits {
//line release_email.qtpl:7
		qw422016.N().S(`
    <tr><a href="`)
//line release_email.qtpl:8
		qw422016.E().S(commit.URL)
//line release_email.qtpl:8
		qw422016.N().S(`">`)
//line release_email.qtpl:8
		qw422016.E().S(commit.Commit.Message)
//line release_email.qtpl:8
		qw422016.N().S(`</a></tr>
    `)
//line release_email.qtpl:9
	}
//line release_email.qtpl:9
	qw422016.N().S(`
  </tbody>
</table>
<p style="margin-top: 2em">
  The previous build was <strong>`)
//line release_email.qtpl:13
	qw422016.E().S(d.currentReleaseTag)
//line release_email.qtpl:13
	qw422016.N().S(`</strong>.
  <br>
  <a href="`)
//line release_email.qtpl:15
	qw422016.E().S(c.URL)
//line release_email.qtpl:15
	qw422016.N().S(`">Compare the releases on Github.</a>
</p>
`)
//line release_email.qtpl:17
}

//line release_email.qtpl:17
func (d *Deployer) writerenderReleaseEmail(qq422016 qtio422016.Writer, newReleaseTag string, c compareResponse) {
//line release_email.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line release_email.qtpl:17
	d.streamrenderReleaseEmail(qw422016, newReleaseTag, c)
//line release_email.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line release_email.qtpl:17
}

//line release_email.qtpl:17
func (d *Deployer) renderReleaseEmail(newReleaseTag string, c compareResponse) string {
//line release_email.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line release_email.qtpl:17
	d.writerenderReleaseEmail(qb422016, newReleaseTag, c)
//line release_email.qtpl:17
	qs422016 := string(qb422016.B)
//line release_email.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line release_email.qtpl:17
	return qs422016
//line release_email.qtpl:17
}
